{
 "title": "Backend App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "GET /user/{id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"GET\"}[1m])))",
     "legendFormat": "{{pod}} (0.5)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"GET\"}[1m])))",
     "legendFormat": "{{pod}} (0.95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"GET\"}[1m])))",
     "legendFormat": "{{pod}} (0.99)"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"GET\"}[1m])))",
     "legendFormat": "{{pod}} (max)"
    }
   ]
  },
  {
   "title": "RPS (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user/.*\", method=\"GET\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user/.*\", status=~\"5..\", method=\"GET\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "POST /user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Latency (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user\",method=\"POST\"}[1m])))",
     "legendFormat": "{{pod}} (0.5)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user\",method=\"POST\"}[1m])))",
     "legendFormat": "{{pod}} (0.95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user\",method=\"POST\"}[1m])))",
     "legendFormat": "{{pod}} (0.99)"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user\",method=\"POST\"}[1m])))",
     "legendFormat": "{{pod}} (max)"
    }
   ]
  },
  {
   "title": "RPS (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user\", method=\"POST\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user\",  status=~\"5..\", method=\"POST\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PUT /user/{id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Latency (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"PUT\"}[1m])))",
     "legendFormat": "{{pod}} (0.5)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"PUT\"}[1m])))",
     "legendFormat": "{{pod}} (0.95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"PUT\"}[1m])))",
     "legendFormat": "{{pod}} (0.99)"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"PUT\"}[1m])))",
     "legendFormat": "{{pod}} (max)"
    }
   ]
  },
  {
   "title": "RPS (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user/.*\", method=\"PUT\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user/.*\", status=~\"5..\", method=\"PUT\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DELETE /user/{id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Latency (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"DELETE\"}[1m])))",
     "legendFormat": "{{pod}} (0.5)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"DELETE\"}[1m])))",
     "legendFormat": "{{pod}} (0.95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"DELETE\"}[1m])))",
     "legendFormat": "{{pod}} (0.99)"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, pod) (irate(http_server_requests_seconds_bucket{uri=~\"/user/.*\",method=\"DELETE\"}[1m])))",
     "legendFormat": "{{pod}} (max)"
    }
   ]
  },
  {
   "title": "RPS (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user/.*\", method=\"DELETE\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(http_server_requests_seconds_count{container=\"backend-app\", uri=~\"/user/.*\", status=~\"5..\", method=\"DELETE\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nginx-Ingress-Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (irate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\", ingress=\"backend-app\"}[1m])))",
     "legendFormat": "{{method}} (0.5)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (irate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\", ingress=\"backend-app\"}[1m])))",
     "legendFormat": "{{method}} (0.95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (irate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\", ingress=\"backend-app\"}[1m])))",
     "legendFormat": "{{method}} (0.99)"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, method) (irate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\", ingress=\"backend-app\"}[1m])))",
     "legendFormat": "{{method}} (max)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by(method) (irate(nginx_ingress_controller_requests{host=\"arch.homework\", ingress=\"backend-app\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum by(method) (irate(nginx_ingress_controller_requests{host=\"arch.homework\", ingress=\"backend-app\", status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory usage (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_memory_working_set_bytes{pod=~\"backend-app-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_cpu_usage_seconds_total{pod=~\"backend-app-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}