apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
data:
  db-url: {{ .Values.configMap.db_url }}
  db-username: {{ .Values.configMap.db_username }}