controller:
  kind: DaemonSet
  
  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

  service:
    type: NodePort